version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: react-docker

    ports:
      - "5173:5173"

    # ðŸ‘‡ IMPORTANT: mount your local code into the container
    volumes:
      - .:/app
      - /app/node_modules

    # optional, but sometimes helps file watching in Docker
    environment:
      - CHOKIDAR_USEPOLLING=true

    command: npm run dev
